const POOL_MIN_STORAGE = ton("10")
const REFUND_THRESHOLD = ton("1")
const MAX_RECOVERY_VALUE = ton("1")
const DEPOSIT_GAS = ton("0.2")
const WITHDRAWAL_GAS = DEPOSIT_GAS
const NEW_VALIDATOR_FEE = ton("0.1")
const PROXY_MIN_STORAGE = ton("10")
const PROXY_INIT_VALUE = ton("0.1")
const PAYOUT_ITEM_BALANCE = ton("0.05")
const PAYOUT_CHAIN_START = ton("0.011")

const RECOVER_STAKE_OK_GAS: int = 50000
const SELF_UPDATE_VSET_GAS = 22000
